import PasswordRecoveryForm from "@/components/PasswordRecoveryForm";
import SimpleLayout from "@/layouts/simpleLayout";
import Head from "next/head";
import React from "react";

function PasswordRecoveryPage() {
  return (
    <SimpleLayout>
      <Head>
        <title>Password Recovery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PasswordRecoveryForm />
    </SimpleLayout>
  );
}

export default PasswordRecoveryPage;
