import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetServerSideProps, NextPage } from 'next'
import { getCostumes, getPopularCostumes } from '@/services/costumes.service'
import { costume } from '@/interfaces/costume'
import NewArrivals from '@/components/NewArrivals'
import PopularModels from '@/components/PopularModels'
import Banner from '@/components/MainBanner'
import HomeSection from '@/components/HomeSection'
import BannerInfo from '@/components/informativeBanner'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  costumes: costume[]
  popularCostume: costume[]
}

const Index: NextPage<Props> = ({ costumes, popularCostume }) => {
  return (
    <>
      <Head>
        <title>Costume Mania</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <HomeSection>
          <Banner></Banner>
        </HomeSection>
        <HomeSection>
          <PopularModels costumes={popularCostume} />
        </HomeSection>
        <HomeSection>
          <BannerInfo bannerInfo={0}></BannerInfo>
        </HomeSection>
        <HomeSection>
          <NewArrivals />
        </HomeSection>
        <HomeSection>
          <BannerInfo bannerInfo={1}></BannerInfo>
        </HomeSection>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query, res }) => {
  const { page = 1 } = query;

  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  const costumes = await getCostumes()
  const popularCostume = await getPopularCostumes()

  return {
    props: {
      costumes,
      popularCostume
    }
  }

}

export default Index