import Breadcrumbs from "@/components/Breadcrumbs";
import RootLayout from "@/layouts/rootLayout";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { AiOutlineHome } from "react-icons/ai";
import { Frijole } from "next/font/google";
import AccountDetailsForm from "@/components/AccountDetailsForm";
import { useSession } from "next-auth/react";
import { fetchDummyUserData } from "@/utils/user";
import Favorites from "@/components/Favorites";
import Purchases from "@/components/Purchases";

const frijole = Frijole({
  subsets: ["latin"],
  weight: "400",
});

export interface UserData {
  email: string;
  firstName: string;
  lastName: string;
  address: string;
  personalId: string;
  birth: string;
  phone: string;
  city: string;
  zipCode: string;
  country: string;
  password: string
}

function AccountPage() {
  const { data: session } = useSession();
  const [user, setUser] = useState<UserData>();

  useEffect(() => {
    if (!session) return;
    const userData = fetchDummyUserData({
      email: session?.user?.email,
      name: session?.user?.name,
    });

    setUser(userData);
  }, [session]);

  return (
    <RootLayout>
      <Head>
        <title>Account details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="min-h-[50%] w-[90vw] px-4 sm:px-6 lg:px-8">
        <h1
          className={`${frijole.className} text-5xl py-4 md:py-6 text-orange-2`}
          style={{ textShadow: "2px 2px 2px rgba(0, 0, 0, 1)" }}
        >
          Account details
        </h1>
        <Breadcrumbs
          homeElement={<AiOutlineHome />}
          separator={<span> / </span>}
          activeClasses="text-amber-500"
          containerClasses="flex py-2 md:py-4 bg-gradient-to-r from-purple-600 to-blue-600 items-center"
          listClasses="hover:underline mx-2 font-bold"
          capitalizeLinks
        />
        <div className="flex flex-col md:flex-row">
          {user && <AccountDetailsForm className="flex-2" account={user} />}
          <aside className="flex flex-col h-full justify-between gap-6 flex-1 m-0 md:ml-12">
            <Favorites />
            <Purchases />
          </aside>
        </div>
      </section>
    </RootLayout>
  );
}

export default AccountPage;
