import RootLayout from "@/layouts/rootLayout";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

function CostumePage() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <RootLayout>
      <Head>
        <title>Costumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Costume ID: {id}</div>;
    </RootLayout>
  );
}

export default CostumePage;
