import { CostumeCardDetail } from "@/components/CostumeDetail";
import CostumesSection from "@/components/CostumesSection";
import { ApiCostume, Costume } from "@/interfaces/costume";
import RootLayout from "@/layouts/rootLayout";
import { getCostume, getPopularCostumes } from "@/services/costumes.service";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React from "react";

interface Props {
  costume: ApiCostume;
  popularCostumes: ApiCostume[];
}

const CostumePage: NextPage<Props> = ({ costume, popularCostumes }) => {
  return (
    <RootLayout>
      <Head>
        <title>Costumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-[90vw] py-8 ">
        <CostumeCardDetail costume={costume} />
        <CostumesSection title="More items to explore" costumes={popularCostumes} />
      </main>
    </RootLayout>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const costumeId = parseInt(query.id as string, 10);
  const costume: Costume = await getCostume(costumeId);
  const popularCostumes = await getPopularCostumes();

  return {
    props: {
      costume,
      popularCostumes,
    },
  };
};

export default CostumePage;
