import Breadcrumbs from "@/components/Breadcrumbs";
import { CostumeCardDetail } from "@/components/CostumeDetail";
import CostumesSection from "@/components/CostumesSection";
import HomeSection from "@/components/HomeSection";
import { ApiCostume, Costume } from "@/interfaces/costume";
import RootLayout from "@/layouts/rootLayout";
import { getCostume, getPopularCostumes } from "@/services/costumes.service";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React from "react";
import { AiOutlineHome } from "react-icons/ai";

interface Props {
  costume: Costume;
  popularCostumes: ApiCostume[];

}

  const CostumePage: NextPage<Props> = ({
    costume,
    popularCostumes,
  }) => {
    console.log('aqui')
    console.log(costume)
    return (
    <RootLayout>
      <Head>
        <title>Costumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>Costume ID: {costume.idModel}</div> */}
      <HomeSection additionalClasses="bg-opacity-20">
      <CostumeCardDetail costume={costume}></CostumeCardDetail>
      </HomeSection>
      <HomeSection>
        <h1 className="text-2xl md:text-3xl font-bold tracking-wider tracking-widest mb-4 text-center">More items to explore</h1>
      <CostumesSection title="" costumes={popularCostumes} />
      </HomeSection>
    </RootLayout>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const costumeId = parseInt(query.id as string, 10);
  const costume: Costume = await getCostume(costumeId);
  const popularCostumes = await getPopularCostumes();
 
  return {
    props: {
      costume,
      popularCostumes,
    },
  };
};

export default CostumePage;