import CostumesList from "@/components/CostumesList";
import Filters from "@/components/Filters";
import { ApiCostume, Category } from "@/interfaces/costume";
import RootLayout from "@/layouts/rootLayout";
import { getCategories } from "@/services/categories.service";
import Head from "next/head";
import React from "react";
import { Frijole } from "next/font/google";
import Breadcrumbs from "@/components/Breadcrumbs";
import { AiOutlineHome } from "react-icons/ai";
import { GetServerSideProps } from "next";
import { getCostumes } from "@/services/costumes.service";
import SearchBar from "@/components/SearchBar";
import Spinner from "@/components/Spinner";
import useCostumesQuery from "@/hooks/useCostumesQuery";

const frijole = Frijole({
  subsets: ["latin"],
  weight: "400",
});

type Props = {
  costumes: ApiCostume[];
  categories: Category[];
};

function CostumesPage({ costumes, categories }: Props) {
  const { data, isRefetching, isError, isLoading } = useCostumesQuery(costumes);

  return (
    <RootLayout>
      <Head>
        <title>Costumes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="min-h-[50%] w-[90vw] px-4 sm:px-6 lg:px-8">
        <h1
          className={`${frijole.className} text-5xl py-4 md:py-6 text-orange-2`}
          style={{ textShadow: "2px 2px 2px rgba(0, 0, 0, 1)" }}
        >
          Costumes
        </h1>
        <Breadcrumbs
          homeElement={<AiOutlineHome />}
          separator={<span> / </span>}
          activeClasses="text-amber-500"
          containerClasses="flex py-2 md:py-4 bg-gradient-to-r from-purple-600 to-blue-600 items-center"
          listClasses="hover:underline mx-2 font-bold"
          capitalizeLinks
        />
        <div className="flex flex-col md:flex-row md:justify-between w-full gap-4 my-4">
          <SearchBar
            className="block md:hidden border-2"
            inputClassName=" focus:outline-none"
            buttonClassName="bg-white text-purple-1"
          />

          <Filters categories={categories} />
          {isRefetching ? <Spinner /> : <CostumesList costumes={data} />}
        </div>
      </section>
    </RootLayout>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const costumes: ApiCostume[] = await getCostumes(query);
  const categories = await getCategories();

  return {
    props: {
      categories,
      costumes,
    },
  };
};

export default CostumesPage;
