import SignUpForm from "@/components/SignUpForm";
import RootLayout from "@/layouts/rootLayout";
import Head from "next/head";
import React from "react";

function SignUpPage() {
  return (
    <RootLayout>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpForm />
    </RootLayout>
  );
}

export default SignUpPage;
